### ISSUE TITLE
Request changes true causes error 

### ISSUE THREAD

**Issue by s-martin** [CatChen/check-git-status-action#633]
Hi,
if I enable request changes I get the following error:

```
gh pr review
  could not determine current branch: failed to run git: not on any branch
  Error: Process completed with exit code 1.
```

Can you give me any hints? Thank you.

**Comment by cafferata** [comment]
> Can you give me any hints? Thank you.

@s-martin, something like this?

```yaml
name: "Check git status"
on:
  pull_request:

jobs:
  check-git-status:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}
    - uses: actions/setup-go@v5
      with:
        go-version: stable
    - run: go mod tidy
    - uses: CatChen/check-git-status-action@v1
      with:
        fail-if-not-clean: true
        request-changes-if-not-clean: true
        request-changes-comment: |
          Please make sure you've run the following commands from the root directory.

          ```shell
          go mod tidy
          ```
```
